# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
X = torch.rand(7,7)
X

tensor([[0.0686, 0.8697, 0.7103, 0.8826, 0.5043, 0.9819, 0.2139],
        [0.1695, 0.4335, 0.9119, 0.4265, 0.3526, 0.7691, 0.8159],
        [0.9341, 0.7614, 0.5165, 0.3322, 0.6704, 0.7163, 0.2580],
        [0.0414, 0.0722, 0.4487, 0.1815, 0.6413, 0.3225, 0.6569],
        [0.1510, 0.2217, 0.1752, 0.1301, 0.5441, 0.0842, 0.7555],
        [0.6758, 0.5723, 0.6957, 0.6734, 0.8945, 0.8417, 0.3716],
        [0.3142, 0.5641, 0.3194, 0.7373, 0.3370, 0.4736, 0.1743]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
Y = torch.rand(1,7)
# Perform matrix multiplication 
torch.matmul(X, Y.T)

tensor([[2.5728],
        [1.8529],
        [2.1389],
        [1.0472],
        [0.9712],
        [2.4740],
        [1.8189]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
TensorA=torch.rand(7,7)
TensorB=torch.rand(1,7)


# Matrix multiply tensors
torch.matmul(TensorA, TensorB.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available else "cpu"
# Create two random tensors on GPU
TensorC = torch.rand(2,3).to(device)
TensorD = torch.rand(2,3).to(device)

TensorC, TensorD

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
TensorE = torch.matmul(TensorC, TensorD.T)

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
max = torch.max(TensorE)
# Find min
min = torch.min(TensorE)
max,min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
print(torch.argmax(TensorE))

# Find arg min
print(torch.argmin(TensorE))


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed(7)

# Create random tensor
TensorF = torch.rand(1,1,1,10)
print(TensorF)
print(f"tensor size: {TensorF.shape}")

# Remove single dimensions
TensorF_squeezed = torch.squeeze(TensorF)

# Print out tensors and their shapes
print(TensorF_squeezed)
print(f"squeezedtensorsize: {TensorF_squeezed.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor size: torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
squeezedtensorsize: torch.Size([10])
