In [17]:
import torch
import torch.nn as nn

In [18]:
a = torch.ones(5, 5)
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [19]:
sum = torch.sum(a, axis=1)
print(sum)

tensor([5., 5., 5., 5., 5.])


In [20]:
b = torch.ones(5, 1)
b

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [21]:
squeezed = torch.squeeze(b)
squeezed

tensor([1., 1., 1., 1., 1.])

In [22]:
unsqueezed = torch.unsqueeze(squeezed, dim=1)
unsqueezed

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])